=== cinthiaBL/XML-Java/sistemas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="sistema">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="clientes"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="clientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cliente" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="cliente">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombrecompleto" type="xs:string"/>
        <xs:element name="edad" type="xs:string"/>
        <xs:element name="numero" type="xs:string"/>
        <xs:element name="categoria" type="xs:string"/>
        <xs:element name="precio" type="xs:string"/>
        <xs:element name="dias" type="xs:string"/>
        <xs:element name="horas" type="xs:string"/>
        <xs:element name="profesor" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cinthiaBL/XML-Java/sistema.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!--Alumnos: Bazan Lopez Cinthia Elizabeth - Rodriguez Guevara Ruben Dali --><sistema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Toshiba/Desktop/Trimestre%2023%20-%20Invierno/Integracion%20de%20sistemas/Proyecto/ProyectoIS/src/proyectois/sistemas.xsd">
                                       

    
    
    
    
    
    
    
    
    <clientes>
                        
        
        
                                    
        
        
        
                    
        
        
        
                    
        
        <cliente id="1200">
                        
            <nombrecompleto>Alonso Reyes Espinosa</nombrecompleto>
                        
            <edad>22</edad>
                        
            <numero>5561734556</numero>
                        
            <categoria>Avanzado</categoria>
                        
            <precio>A: $799</precio>
                        
            <dias>Martes y Jueves</dias>
                        
            <horas>11:00 a 14:00</horas>
                        
            <profesor>Alejandra Velazquez Quiroga</profesor>
                    
        </cliente>
            
        <cliente id="1200">
            <nombrecompleto>uben Dali Rodriguez Guevara</nombrecompleto>
            <edad>23</edad>
            <numero>5578906534</numero>
            <categoria>Intermedio</categoria>
            <precio>I: $560</precio>
            <dias>Martes y Jueves</dias>
            <horas>11:00 a 14:00</horas>
            <profesor>Javier Lopez Hernandez</profesor>
        </cliente>
    </clientes>
                            






</sistema>
